const fs = require('fs');
const path = require('path');
const dir = 'c:/kernal/MCA/project/portfolio/src/components';
const file = 'Metrics.jsx';
const filePath = path.join(dir, file);
let content = fs.readFileSync(filePath, 'utf8');
content = content.replace(/\\`/g, '`');
content = content.replace(/\\\$/g, '$');
fs.writeFileSync(filePath, content);
console.log('Fixed syntax in Metrics.jsx');
